//GET actions
export const MANIFESTS_SEARCH_REQ = 'MANIFESTS_SEARCH_REQ';
export const MANIFESTS_SEARCH_RES = 'MANIFESTS_SEARCH_RES';
export const MANIFESTS_SEARCH_ERR = 'MANIFESTS_SEARCH_ERR';

//DELETE actions
export const MANIFESTS_DELETE_REQ = 'MANIFESTS_DELETE_REQ';
export const MANIFESTS_DELETE_RES = 'MANIFESTS_DELETE_RES';
export const MANIFESTS_DELETE_ERR = 'MANIFESTS_DELETE_ERR';